# Generated by Django 5.0.3 on 2024-03-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
