# Generated by Django 5.0.3 on 2024-03-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
